### ISSUE TITLE
RFE: Add repeat handling for X11 keyboard remote control

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#18]
can you please integrate the new keyboard handling also

https://www.vdr-portal.de/forum/index.php?thread/132771-patch-repeat-function-f%C3%BCr-vaapidevice/&postID=1315760#post1315760

https://github.com/rofafor/vdr-plugin-vaapidevice/commit/d19657bae399e79df107e316ca40922d21393f80

**Comment by jojo61** [comment]
ok done

**Comment by 9000h** [comment]
thanks
