### ISSUE TITLE
vulkan question

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#2]
in reference to http://vulkan.gpuinfo.org, is there any chance to get this also working for Intel GFX

**Comment by jojo61** [comment]
The libplacebo part may work also with Intel GFX, but the cuda decoder certainly not.  
I think about enabling vdpau decoder for AMD cards as they also decode 16 Bit HEVC. The output via libplacebo should not be affected by the decoder. For Intel I think I would need vaapi and there is already a good plugin available for this.

**Comment by 9000h** [comment]
thanks
