### ISSUE TITLE
core crash on channel ARTI TV

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#22]
in reference to
https://github.com/jojo61/vdr-plugin-softhdcuvid/blob/5cd68b6eed98bc2ec2320798f7f6f89c15c487bf/video.c#L4265

there seem to be a issue with the surface as the max got it here with this cannel, I could not find any other.

**Comment by 9000h** [comment]
to verfiy the issue I did a small recording
[arti-tv.zip](https://github.com/jojo61/vdr-plugin-softhdcuvid/files/3880778/arti-tv.zip)

**Comment by jojo61** [comment]
This is an issue with FFMPEG. The deint filter for vaapi does not provide correct PTS timestamps for the second frame. You can also see this with CNN. I could prevent the crash but that does not solve the problem. I did not check how other plugins solved the issue. Most likly they don't use the vaapi deint filter.

**Comment by 9000h** [comment]
would AVFMT_FLAG_GENPTS of any help?

**Comment by jojo61** [comment]
I did not test this. I will look into this when I am ready with the HDR functionality. At the moment this issue has no priority for me.

**Comment by jojo61** [comment]
I investigated this now and I can't solve the issue. The FFMPEG VAAPI decoder does not provide PTS and I can't change this. It happens on TV stations that seem to send invalid/stange streams.
This needs to be fixed at the VAAPI decoder side.

**Comment by 9000h** [comment]
ok thanks

**Comment by 9000h** [comment]
btw with the softhddrm it did not look nice but there is no crash
