### ISSUE TITLE
c++ issues

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#33]
The class 'cOglOutputFb' defines member variable with name 'initiated' also defined in its parent class 'cOglFb'. 
also valid for fb and textures

in openglosd.cpp:1
#define __STL_CONFIG_H
macro name is a reserved identifier [Lexical or Preprocessor Issue]

**Comment by jojo61** [comment]
#define __STL_CONFIG_H
There was a discussion that this may be needed. As it does not generate any problems and I do not know why it is really there I will not change it.

The overlapping variables also do no harm and I will not change it.
