### ISSUE TITLE
possible type issue

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#35]
it may has to be "int" as it's later uses as int
https://github.com/jojo61/vdr-plugin-softhdcuvid/blob/6c0f80979f0406ceceef2fc196a88a99f1e613a7/openglosd.h#L207

**Comment by jojo61** [comment]
I do not find where it is used as int. Everywhere it is defined as GLint.

**Comment by 9000h** [comment]
it's probably no issue as GLint is defined as int
