### ISSUE TITLE
No black screen for radio

### ISSUE THREAD

**Issue by REELcoder** [jojo61/vdr-plugin-softhdcuvid#44]
When I switch to a radio channel with audio only, the screen is not getting black, but the last image from the old channel stays.

softhdcuvid.BlackPicture and softhdcuvid.ClearOnSwitch are enabled...

Any Ideas how to fix this?

**Comment by jojo61** [comment]
This problem is already known and I have no intention to fix it.

**Comment by REELcoder** [comment]
Is there some more info about it (e.g. forum discussion)? What would have to be changed?

**Comment by jojo61** [comment]
In order to fix this I would need to distinguish between live play and record play. In record play I need to update the picture during jumps. In live play I would need to generate a black screen. With vulkan this is not so easy anymore.

**Comment by jojo61** [comment]
Fix for Radio Plugin comitted
