### ISSUE TITLE
[softhdvaapi] 4:3 streams are autocropped to full screen

### ISSUE THREAD

**Issue by DrStrangeHH** [jojo61/vdr-plugin-softhdcuvid#48]
...although "4:3 video display format" is configured to 'letterbox' and softhddevice.AutoCrop.Interval = 0 in setup.conf
Note: This bug does not appear in softhdcuvid

**Comment by jojo61** [comment]
I can not reproduce this. As the cropping has changed recently try to update on test again.
If this still happens, please provide a small sample of the stream for testing.

**Comment by dnehring7** [comment]
I'm 99,9% sure that this is not correct. Here is the code:
[https://github.com/jojo61/vdr-plugin-softhdcuvid/blob/master/video.c#L712](url)

As you see, the switch works as the 16:9 ZoomMode.

**Comment by DrStrangeHH** [comment]
I can't find an example for 4:3 fullscreen (in the meantime I upgraded to Ubuntu 20.04), but there are several (not all) 4:3 recordings where the bottom half is full with glitches/artefacts. I attach an example.

[%%%Moskau.zip](https://github.com/jojo61/vdr-plugin-softhdcuvid/files/4565481/Moskau.zip)

**Comment by DrStrangeHH** [comment]
jetzt habe ich doch noch eine 4:3-Aufnahme gefunden, dies störungsfrei läuft, aber auf 16:9 aufgezoomt wird
[%%%Mit_Dieter_Thomas_Heck.zip](https://github.com/jojo61/vdr-plugin-softhdcuvid/files/4565573/Mit_Dieter_Thomas_Heck.zip)

**Comment by dnehring7** [comment]
I've tested your example with my setup, no problem, correct scaling, left and right black border. Perhaps your TV has some autodetections of 4:3 content. We should close the issue.

Special scaling options for 4:3 is nowadays a corner case, we should drop this feature anyway from the source.
