### ISSUE TITLE
[softhdvaapi]: broken audio on 1080i channels

### ISSUE THREAD

**Issue by DrStrangeHH** [jojo61/vdr-plugin-softhdcuvid#49]
For example Sky Sport News HD (which is a FreeTV-channel): audio appears every few seconds for a few seconds. Same on all other 1080i channels supplied by Vodafone Cable
Note: This bug does not appear with softhdcuvid

**Comment by jojo61** [comment]
I can not reproduce this beavior. Could you provide a small sample of video with this problem ?

**Comment by DrStrangeHH** [comment]
[@Live_Sky_Sport_News_HD:_Abendreport_Sky_Sport_News_HD_Abendreport.zip](https://github.com/jojo61/vdr-plugin-softhdcuvid/files/4565363/%40Live_Sky_Sport_News_HD._Abendreport_Sky_Sport_News_HD_Abendreport.zip)

Ich habe ein paar Sekunden hochgeladen. Im vlc-Player lässt es sich abspielen.
