### ISSUE TITLE
libplacebo causes high CPU load and can't be turned off on HD channels

### ISSUE THREAD

**Issue by DrStrangeHH** [jojo61/vdr-plugin-softhdcuvid#51]
No matter which of the available scalers is choosed - process vdr is always at around 50% CPU load on Nvidia (softhdcuvid) and 25% on Intel (softhdvaapi) - not completly comparable because the two machines have different hardware.  But with softhddevice it is only 5%

On a FullHD TV I don't need deinterlacing for 720p streams. It should be possible to turn off Scaling, but currently there are only different methods and no entry for OFF.

**Comment by jojo61** [comment]
Yes I can see on my NUC that with placebo the load is high. This can not be changed and I can not switch off placebo for certain channels. The only option is to compile without placebo.
It seems that vulkan is on Intel slower than on NVIDIA systems.
