### ISSUE TITLE
libplacebo API change: compile errors

### ISSUE THREAD

**Issue by stegro4712** [jojo61/vdr-plugin-softhdcuvid#52]
Using the libplacebo from Ubuntu  focal (API Version 7) is hindering a compilation.
I set in the Makefile: VAAPI = 1

Below a list of errors:

video.c:2346:14: error: ‘struct pl_tex_params’ has no member named ‘import_handle’
 2346 |             .import_handle = PL_HANDLE_DMA_BUF,
      |              ^~~~~~~~~~~~~
video.c:2346:30: error: ‘PL_HANDLE_DMA_BUF’ undeclared (first use in this function)
 2346 |             .import_handle = PL_HANDLE_DMA_BUF,
      |                              ^~~~~~~~~~~~~~~~~
video.c:2347:14: error: ‘struct pl_tex_params’ has no member named ‘shared_mem’
 2347 |             .shared_mem = (struct pl_shared_mem) {

video.c: In function ‘CuvidMixVideo’:
video.c:3681:23: error: ‘struct pl_color_space’ has no member named ‘sig_scale’
 3681 |             img->color.sig_scale = 1.0f;

video.c:3684:26: error: ‘struct pl_render_params’ has no member named ‘peak_detect_params’
 3684 |             render_params.peak_detect_params = NULL;

video.c: In function ‘InitPlacebo’:
video.c:5236:17: error: ‘const struct pl_gpu’ has no member named ‘import_caps’
 5236 |     if (!(p->gpu->import_caps.tex & PL_HANDLE_DMA_BUF)) {
      |                 ^~
video.c:5236:37: error: ‘PL_HANDLE_DMA_BUF’ undeclared (first use in this function)
 5236 |     if (!(p->gpu->import_caps.tex & PL_HANDLE_DMA_BUF)) {
      |                                     ^~~~~~~~~~~~~~~~~

**Comment by dnehring7** [comment]
My PL_API_VER is 29...

Seems your installation is a little bit ancient, the variable ist from 2018:

git blame gpu.h:
...
8dea6887 src/include/libplacebo/gpu.h (Philip Langdale 2018-12-04 23:30:17 -0800   58)     PL_HANDLE_FD        = (1 << 0), // `int fd` for P
OSIX-style APIs
8dea6887 src/include/libplacebo/gpu.h (Philip Langdale 2018-12-04 23:30:17 -0800   59)     PL_HANDLE_WIN32     = (1 << 1), // `HANDLE` for win32 API
8dea6887 src/include/libplacebo/gpu.h (Philip Langdale 2018-12-04 23:30:17 -0800   60)     PL_HANDLE_WIN32_KMT = (1 << 2), // `HANDLE` for pre-Windows-8 win32 API
39f4809d src/include/libplacebo/gpu.h (Philip Langdale 2018-12-14 09:06:09 +0800   61)     PL_HANDLE_DMA_BUF   = (1 << 3), // 'int fd' for a dma_buf fd
7b2b5980 src/include/libplacebo/gpu.h (Niklas Haas     2018-10-30 22:56:13 +0100   62) };
