### ISSUE TITLE
RFE mediaplayer

### ISSUE THREAD

**Issue by 9000h** [jojo61/vdr-plugin-softhdcuvid#56]
do you think it makes sense to add a media player function like
https://github.com/zillevdr/vdr-plugin-softhddevice-drm/blob/drm/mediaplayer.cpp

**Comment by jojo61** [comment]
What is it good for.  I think vdr is not a multimedia player. Kodi is the better solution for this.
With opening the possibility to play  arbitrary files we open up all sorts of codec problems that are not handles at the moment.

**Comment by 9000h** [comment]
thanks
