### ISSUE TITLE
Fails to build on Arch

### ISSUE THREAD

**Issue by M-Reimer** [jojo61/vdr-plugin-softhdcuvid#59]
I don't know which library is responsible (on Arch usually everything is always "bleeding edge" so latest versions).

I get the following when compiling on an up-to-date Arch system:

```
video.c: In function ‘CuvidMixVideo’:
video.c:4114:8: error: ‘struct pl_color_adjustment’ has no member named ‘temperature’
 4114 |  colors.temperature = VideoTemperature;
      |        ^
```

**Comment by M-Reimer** [comment]
Update: Ignore above error. Had to update to the latest GIT version and now this one seems to be gone. Now I fail here:

```
video.c:2464:22: error: ‘struct pl_shared_mem’ has no member named ‘stride_h’
 2464 |                     .stride_h = n == 0 ? image_height : image_height / 2,
      |                      ^~~~~~~~
video.c:2465:22: error: ‘struct pl_shared_mem’ has no member named ‘stride_w’
 2465 |                     .stride_w = desc.layers[n].pitch[0],
      |                      ^~~~~~~~
```

**Comment by M-Reimer** [comment]
Oh. And it seems like on Arch the libplacebo package is not that well maintained. I'm stuck at version 3.104.0 on Arch.

**Comment by jojo61** [comment]
Seems you need an updated libplacebo.
