### ISSUE TITLE
Threads and Handler mixed up

### ISSUE THREAD

**Issue by sistlind** [jojo61/vdr-plugin-softhdcuvid#61]
Ist es Absicht, dass bei Videothread und VideoDisplaythread die Handler vertauscht sind?

https://github.com/jojo61/vdr-plugin-softhdcuvid/blob/59a82d409eea64ca0d471683f7c05bb63503b10e/video.c#L5920-L5922

**Comment by jojo61** [comment]
Ja da ist es etwas durcheinander
