### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by M-Reimer** [jojo61/vdr-plugin-softhdcuvid#63]
For vdr4arch I'm still at release 3.5 which is the last release that was tagged.

Now I've seen that you "silently" continued increasing the revision number without actually tagging a release:
https://github.com/jojo61/vdr-plugin-softhdcuvid/commit/fefd3e83f6d60eae40f45ed2f7423dc896c75b8f

So now I actually don't know what to do here. I could hack something together to download a commit snapshot and just name it with the correct release. But the proper way would be that you tag releases whenever you create one so release tarballs can be downloaded from GitHub.

**Comment by jojo61** [comment]
Made Version 3.6
