### ISSUE TITLE
softhdvaapi broken with newest libplacebo on ihd

### ISSUE THREAD

**Issue by geraldraaf** [jojo61/vdr-plugin-softhdcuvid#64]
after updating my gentoo system vdr-2.5.6 and softhdvaapi don't work any longer, i got a black screen with working sound.

Some SW Info
vdr version 2.5.6
softhdcuvid latest git version
libplacebo 4.192.1 also tested latest git version from today

i tracked down which commit in libplacebo breaks viewing tv.

this was the last commit version that works
d262aa8e306e152000d38d49eb1d3286044eadc2

with the next commit version i get black screen with sound.
12a1f6566076fe881267137d9f42b0a1acfb45f6

in the Makefile i have enabled 
VAAPI
and LIBPLACEBO_GL

When i enable LIBPLACEBO and disabled LIBPLACEBO_GL i alse have a black screen, Only LIBPLACEBO never worked for me.

**Comment by jojo61** [comment]
I do not support the latest libplacebo. As I anyway do not use newer features you need to use libplacebo from Mai 21.
