### ISSUE TITLE
Automatic tagging of version changes

### ISSUE THREAD

**Issue by tmn505** [jojo61/vdr-plugin-softhdcuvid#68]
The project versions change but there's no tag following it, which makes it difficult for distro maintainers. I don't know what's the exact policy on version tagging but I would like to request for a tag on each version change. To make this automated You can put in `.git/hooks` following script:
```bash
#!/usr/bin/env bash

version="$(git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)/softhdcuvid.cpp" | sed -n -e '/^+.*VERSION/ s/[^0-9\.]//gp')"

if [[ ! ${version} =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)?$ ]]; then
        if [ -n "${version}" ]; then
                printf 'Skip tag: invalid version %s\n' "${version}"
        fi
        exit 1
fi

git tag "V${version}"
printf 'Created a new tag, V%s\n' "${version}"
```
It will create un-annotated tag on each `VERSION` change in `softhdcuvid.cpp`. Also to automatically include tags on every push to GH repository, invoke `git config push.followTags true`.

This will make it easier for us, as packagers. Thanks

Related: #57 #63

**Comment by jojo61** [comment]
Ok I put the file into .git/hooks  Hopefully that works now.
