### ISSUE TITLE
build failure with libplacebo 6.338

### ISSUE THREAD

**Issue by pixelpeter67** [jojo61/vdr-plugin-softhdcuvid#72]
softhdcuvid.cpp: In member function ‘void cMenuSetupSoft::Create()’:
softhdcuvid.cpp:1156:27: error: ‘pl_named_filters’ was not declared in this scope
 1156 |         for (scalers = 0; pl_named_filters[scalers].name != NULL; scalers++) {
      |                           ^~~~~~~~~~~~~~~~
make[1]: *** [<eingebaut>: softhdcuvid.o] Fehler 1

**Comment by M-Reimer** [comment]
This issue makes it currently impossible to ship this plugin for Arch.
https://archlinux.org/packages/extra/x86_64/libplacebo/
`libplacebo 6.338.2-1`

**Comment by jojo61** [comment]
This should work now with the latest Release
